---
version: "2.1"
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /plex/config:/config
      - /plex/transcode:/transcode
      - /plexmedia/media:/data
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
